### ISSUE TITLE
Delete old windows installation when updating

### ISSUE THREAD

**Issue by ziproot** [tibetiroka/ESManager#1]
If you try to update the game on windows in a case where a file is in the data folder that has been removed upstream, ESManager will not remove that file. ESManager should move the old windows installation to a backup, replacing a previous backup if it exists, and delete the old windows installation once it has confirmed that there is a new one upstream.

**Comment by ziproot** [comment]
See https://github.com/EndlessSkyCommunity/ESLauncher2/issues/82#issue-733927494 for a similar issue with ESLauncher2

**Comment by tibetiroka** [comment]
Which version of ESManager are you using? Which option did you choose to obtain the executable?

**Comment by tibetiroka** [comment]
Okay, I'm going to assume you used the default "Latest Release" option when creating your instance, as that's the only one I can reproduce the issue with.  This should be fixed by dc0db4931ece9ba3ab44325dc1bb56422f7f395a.

The new version puts the downloads in a temporary directory, then moves the current one to a backup, and either deletes or restores the backup based on whether the downloads could be moved to their proper place. This system, while isn't foolproof, shouldn't really break in practice. (There are some edge cases with file system moves failing as I don't verify the files before/after moving them, so partial moves would mess things up, but that's not something I can really handle here. Stuff like that.)

I did some small tests and it seems to work. One thing to note here is that this will not fix your existing instances until the next update, so if you have any instances that are currently broken, you will need to delete and re-create them.

If this was indeed how you ran into the issue, I can push a new release with this bugfix.

**Comment by ziproot** [comment]
I did indeed use the latest release option.
